package com.jesus.apilol.models.entities;

// default package
// Generated 12 abr. 2021 18:30:05 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Administradores generated by hbm2java
 */
@Entity
@Table(name = "administradores", uniqueConstraints = { @UniqueConstraint(columnNames = "correo"),
		@UniqueConstraint(columnNames = "usuario") })
public class Administradores implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idAdministrador;
	private String correo;
	private String usuario;
	private String password;

	public Administradores() {
	}

	public Administradores(int idAdministrador, String correo, String usuario, String password) {
		this.idAdministrador = idAdministrador;
		this.correo = correo;
		this.usuario = usuario;
		this.password = password;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id_administrador", unique = true, nullable = false)
	public int getIdAdministrador() {
		return this.idAdministrador;
	}

	public void setIdAdministrador(int idAdministrador) {
		this.idAdministrador = idAdministrador;
	}

	@Column(name = "correo", unique = true, nullable = false, length = 50)
	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	@Column(name = "usuario", unique = true, nullable = false, length = 20)
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	@Column(name = "password", nullable = false, length = 20)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
