package com.jesus.apilol.models.entities;

// default package
// Generated 12 abr. 2021 18:30:05 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Campeones generated by hbm2java
 */
@Entity
@Table(name = "campeones", uniqueConstraints = @UniqueConstraint(columnNames = "nombre"))
public class Campeones implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idCampeon;
	private Roles roles;
	private String nombre;
	private String descripcion;
	private int dificultad;
	private String imagen;
	private String posicion;
	private Set<Habilidades> habilidadeses = new HashSet<Habilidades>(0);

	public Campeones() {
	}

	public Campeones(int idCampeon, String nombre, String descripcion, int dificultad) {
		this.idCampeon = idCampeon;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.dificultad = dificultad;
	}

	public Campeones(int idCampeon, Roles roles, String nombre, String descripcion, int dificultad, String imagen,
			String posicion, Set<Habilidades> habilidadeses) {
		this.idCampeon = idCampeon;
		this.roles = roles;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.dificultad = dificultad;
		this.imagen = imagen;
		this.posicion = posicion;
		this.habilidadeses = habilidadeses;
	}

	@Id
	@Column(name = "id_campeon", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.IDENTITY, generator="secuencia")
    @SequenceGenerator(name="secuencia", sequenceName = "secuencia_campeones",allocationSize = 1)
	public int getIdCampeon() {
		return this.idCampeon;
	}

	public void setIdCampeon(int idCampeon) {
		this.idCampeon = idCampeon;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JsonIgnoreProperties({"campeoneses"})
	@JoinColumn(name = "id_rol")
	public Roles getRoles() {
		return this.roles;
	}

	public void setRoles(Roles roles) {
		this.roles = roles;
	}

	@Column(name = "nombre", unique = true, nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", nullable = false, length = 2000)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "dificultad", nullable = false)
	public int getDificultad() {
		return this.dificultad;
	}

	public void setDificultad(int dificultad) {
		this.dificultad = dificultad;
	}

	@Column(name = "imagen", length = 1000000)
	public String getImagen() {
		return this.imagen;
	}

	public void setImagen(String imagen) {
		this.imagen = imagen;
	}

	@Column(name = "posicion", length = 20)
	public String getPosicion() {
		return this.posicion;
	}

	public void setPosicion(String posicion) {
		this.posicion = posicion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "campeones")
	@JsonIgnoreProperties({"campeones"})
	public Set<Habilidades> getHabilidadeses() {
		return this.habilidadeses;
	}

	public void setHabilidadeses(Set<Habilidades> habilidadeses) {
		this.habilidadeses = habilidadeses;
	}

}
