package com.jesus.apilol.models.entities;

// default package
// Generated 12 abr. 2021 18:30:05 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Habilidades generated by hbm2java
 */
@Entity
@Table(name = "habilidades", uniqueConstraints = @UniqueConstraint(columnNames = "nombre_habilidad"))
public class Habilidades implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idHabilidad;
	private Campeones campeones;
	private String nombreHabilidad;
	private String descripcionHabilidad;
	private String letraHabilidad;

	public Habilidades() {
	}

	public Habilidades(int idHabilidad, String nombreHabilidad) {
		this.idHabilidad = idHabilidad;
		this.nombreHabilidad = nombreHabilidad;
	}

	public Habilidades(int idHabilidad, Campeones campeones, String nombreHabilidad, String descripcionHabilidad,
			String letraHabilidad) {
		this.idHabilidad = idHabilidad;
		this.campeones = campeones;
		this.nombreHabilidad = nombreHabilidad;
		this.descripcionHabilidad = descripcionHabilidad;
		this.letraHabilidad = letraHabilidad;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id_habilidad", unique = true, nullable = false)
	public int getIdHabilidad() {
		return this.idHabilidad;
	}

	public void setIdHabilidad(int idHabilidad) {
		this.idHabilidad = idHabilidad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JsonIgnoreProperties({"habilidadeses","roles","nombre","descripcion","dificultad","imagen","posicion"})
	
	@JoinColumn(name = "id_campeon")
	public Campeones getCampeones() {
		return this.campeones;
	}

	public void setCampeones(Campeones campeones) {
		this.campeones = campeones;
	}

	@Column(name = "nombre_habilidad", unique = true, nullable = false, length = 50)
	public String getNombreHabilidad() {
		return this.nombreHabilidad;
	}

	public void setNombreHabilidad(String nombreHabilidad) {
		this.nombreHabilidad = nombreHabilidad;
	}

	@Column(name = "descripcion_habilidad", length = 200)
	public String getDescripcionHabilidad() {
		return this.descripcionHabilidad;
	}

	public void setDescripcionHabilidad(String descripcionHabilidad) {
		this.descripcionHabilidad = descripcionHabilidad;
	}

	@Column(name = "letra_habilidad", length = 10)
	public String getLetraHabilidad() {
		return this.letraHabilidad;
	}

	public void setLetraHabilidad(String letraHabilidad) {
		this.letraHabilidad = letraHabilidad;
	}

}
