package com.jesus.apilol.models.entities;

// default package
// Generated 12 abr. 2021 18:30:05 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Roles generated by hbm2java
 */
@Entity
@Table(name = "roles")
public class Roles implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idRol;
	private String nombreRol;
	private Set<Campeones> campeoneses = new HashSet<Campeones>(0);

	public Roles() {
	}

	public Roles(int idRol, String nombreRol) {
		this.idRol = idRol;
		this.nombreRol = nombreRol;
	}

	public Roles(int idRol, String nombreRol, Set<Campeones> campeoneses) {
		this.idRol = idRol;
		this.nombreRol = nombreRol;
		this.campeoneses = campeoneses;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id_rol", unique = true, nullable = false)
	public int getIdRol() {
		return this.idRol;
	}

	public void setIdRol(int idRol) {
		this.idRol = idRol;
	}

	@Column(name = "nombre_rol", nullable = false, length = 20)
	public String getNombreRol() {
		return this.nombreRol;
	}

	public void setNombreRol(String nombreRol) {
		this.nombreRol = nombreRol;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "roles")
	@JsonIgnoreProperties({"roles"})
	
	public Set<Campeones> getCampeoneses() {
		return this.campeoneses;
	}

	public void setCampeoneses(Set<Campeones> campeoneses) {
		this.campeoneses = campeoneses;
	}

}
